/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author thewi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_realizarDenuncia = new javax.swing.JButton();
        b_mapaAglomeracoes = new javax.swing.JButton();
        b_alterarIdioma = new javax.swing.JButton();
        b_reportarBugs = new javax.swing.JButton();
        b_enviarSugestoes = new javax.swing.JButton();
        b_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ferramenta de denúncias COVID-19");
        setPreferredSize(new java.awt.Dimension(900, 600));

        b_realizarDenuncia.setText("Realizar uma denúncia");
        b_realizarDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_realizarDenunciaActionPerformed(evt);
            }
        });

        b_mapaAglomeracoes.setText("Exibir mapa de aglomerações (EM BREVE)");
        b_mapaAglomeracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mapaAglomeracoesActionPerformed(evt);
            }
        });

        b_alterarIdioma.setText("Alterar idioma");
        b_alterarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarIdiomaActionPerformed(evt);
            }
        });

        b_reportarBugs.setText("Reportar bugs");
        b_reportarBugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reportarBugsActionPerformed(evt);
            }
        });

        b_enviarSugestoes.setText("Enviar sugestões");
        b_enviarSugestoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enviarSugestoesActionPerformed(evt);
            }
        });

        b_sair.setText("Sair");
        b_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_realizarDenuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_mapaAglomeracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_alterarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(b_reportarBugs, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(b_enviarSugestoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(b_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(b_realizarDenuncia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_mapaAglomeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_alterarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_reportarBugs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_enviarSugestoes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_realizarDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_realizarDenunciaActionPerformed
        RealizarDenuncia realizardenuncia = new RealizarDenuncia();
        realizardenuncia.setVisible(true);
    }//GEN-LAST:event_b_realizarDenunciaActionPerformed

    private void b_mapaAglomeracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mapaAglomeracoesActionPerformed
        JOptionPane.showMessageDialog(null,"Esta opção ainda não disponível.","EM BREVE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b_mapaAglomeracoesActionPerformed

    private void b_alterarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarIdiomaActionPerformed
        AlterarIdioma alteraridioma = new AlterarIdioma();
        alteraridioma.setVisible(true);
    }//GEN-LAST:event_b_alterarIdiomaActionPerformed

    private void b_reportarBugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reportarBugsActionPerformed
        ReportarBug reportarbug = new ReportarBug();
        reportarbug.setVisible(true);
    }//GEN-LAST:event_b_reportarBugsActionPerformed

    private void b_enviarSugestoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_enviarSugestoesActionPerformed
        EnviarSugestao enviarsugestao = new EnviarSugestao();
        enviarsugestao.setVisible(true);
    }//GEN-LAST:event_b_enviarSugestoesActionPerformed

    private void b_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_b_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterarIdioma;
    private javax.swing.JButton b_enviarSugestoes;
    private javax.swing.JButton b_mapaAglomeracoes;
    private javax.swing.JButton b_realizarDenuncia;
    private javax.swing.JButton b_reportarBugs;
    private javax.swing.JButton b_sair;
    // End of variables declaration//GEN-END:variables
}
